### ISSUE TITLE
Automate reporting here

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/State-of-the-Bay#17]
This sentence is ripe for integrated R code to automate updates.
https://github.com/tbep-tech/State-of-the-Bay/blob/900cb075a5f3711770517f6bc6f6055fa311984c/doc/clean-waters-and-sediments.md?plain=1#L29

**Comment by fawda123** [comment]
Mostly done up to this commit 243851cf988feb6fc8243b6ae90b4492f8962486
