### ISSUE TITLE
review habitat restoration

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/State-of-the-Bay#26]
Now that the draft pages are complete, please review them for any final edits that may be needed, including text, graphics/tables, and layout... this is the final round of edits before it goes "live". Things to consider:

* Does the text make sense? Are there any errors that need to be corrected?
* How do the graphics/tables look? Do they send a simple, high-level summary appropariate for the SOB? Are there other graphics that we could add?
* Is the layout ok (e.g., presentation of ideas, section labels, pictures to include, graph sizing , etc.)?

Page to review: https://tbep-tech.github.io/State-of-the-Bay/docs/habitat-restoration

You can make edits to the Rmd file here: https://github.com/tbep-tech/State-of-the-Bay/blob/master/docs/habitat-restoration.Rmd

Or just comment on this issue with things you'd like to see changed.

If you're happy with the existing page, just close this issue.

And don't forget to use the Project board to track progress on this issue: https://github.com/tbep-tech/State-of-the-Bay/projects/3

**Comment by sscolaro** [comment]
@Gmangrove @fawda123 You are going to hate me when I say this, but can we make the HMPU section where you outline the important targets more visual? Maybe instead of the bullet, we can develop an infographic to represent the different habitats and targets? I also think the table would be better represented as a graph so people can see how much uplands are being lost to development.

**Comment by fawda123** [comment]
@sscolaro I agree that this would a nice addition.  Maybe easiest thing to do for now is to add some pics of the Rock Ponds.  @Gmangrove or @Tbep-Joe, do we have any good before/after pics for this?  An infographic would be nice, but I'm probably not the right one to take the lead on that.

**Comment by Gmangrove** [comment]
To get to @sscolaro 's thought about the 'vastness', maybe a couple of pics from google earth, ca 2010 and now (attached quick examples) - Caption something along the lines of "The Rock Ponds Restoration Project created or restored 1,043 acres of  habitat, including mangroves, salt marshes, and coastal uplands. The Southwest Florida Water Management District led the effort, and multiple other organizations including TBEP were significant contributors. Pictures are pre-restoration (2010, left) and post-restoration (2021, right)."

![RockPonds_20100404](https://user-images.githubusercontent.com/49997266/151357860-d38a2698-a2c5-4491-a7d0-63774d2e6abf.png)
![RockPonds_20210506](https://user-images.githubusercontent.com/49997266/151357861-ef88b0b7-f635-4aba-8727-ec76163fddfd.png)
?

**Comment by Gmangrove** [comment]
And I'll try to hunt up some really good before/after pics, maybe the Safety Harbor project

**Comment by sscolaro** [comment]
@Gmangrove I think just a good habitat restoration picture would be adequate for now. I think it just needs more visuals ;)

**Comment by Gmangrove** [comment]
Maybe to low-res, but very shortly after planting (with Reddish egret) and then maybe 1-year post planting.

![RE_at_Safety_Harbor_gr](https://user-images.githubusercontent.com/49997266/151605439-656cca6f-c5ba-42d6-8ccf-74fc3ef51c5e.jpg)
![Safety_Harbor_gr](https://user-images.githubusercontent.com/49997266/151605441-371f85ed-4ba8-450d-a8f8-6e15a38813d5.jpg)

**Comment by sscolaro** [comment]
What about a pic from the Robinson restoration site or the iconic Rock Ponds one from Unsplash?
![the-tampa-bay-estuary-program-oabh9iFf1-U-unsplash](https://user-images.githubusercontent.com/72457078/151607377-1ca4712a-a579-41ed-aa25-4d0ce74f7260.jpg)
![the-tampa-bay-estuary-program-CnUGhhVWK4I-unsplash](https://user-images.githubusercontent.com/72457078/151607384-008a5145-d170-48ea-932b-fbf89e4b5bc6.jpg)

**Comment by sscolaro** [comment]
@Tbep-Joe Perfect!!

**Comment by Gmangrove** [comment]
Bueno @Tbep-Joe !

**Comment by fawda123** [comment]
Thanks y'all, check it: https://tbep-tech.github.io/State-of-the-Bay/docs/habitat-restoration

@Gmangrove can you close this issue if it looks good?

**Comment by Gmangrove** [comment]
I'm gonna close the issue but I need to update the restoration table thru 2021 - https://drive.google.com/file/d/1zVx18P6lrPuVR6ANMAetBRXwxCGeCN9b/view

**Comment by fawda123** [comment]
@Gmangrove just ping me in Slack when the update is ready
