### ISSUE TITLE
review grants awarded

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/State-of-the-Bay#30]
Now that the draft pages are complete, please review them for any final edits that may be needed, including text, graphics/tables, and layout... this is the final round of edits before it goes "live". Things to consider:

* Does the text make sense? Are there any errors that need to be corrected?
* How do the graphics/tables look? Do they send a simple, high-level summary appropariate for the SOB? Are there other graphics that we could add?
* Is the layout ok (e.g., presentation of ideas, section labels, pictures to include, graph sizing , etc.)?

Page to review: https://tbep-tech.github.io/State-of-the-Bay/docs/grants-awarded.html

You can make edits to the Rmd file here: https://github.com/tbep-tech/State-of-the-Bay/blob/master/docs/grants-awarded.Rmd

Or just comment on this issue with things you'd like to see changed.

If you're happy with the existing page, just close this issue.

And don't forget to use the Project board to track progress on this issue: https://github.com/tbep-tech/State-of-the-Bay/projects/3

**Comment by sscolaro** [comment]
@fawda123 The sums for the BMG total number of grants awarded and amount awarded are off. Amount awarded should be around $2.05 mil and grants should be 426.

I think the License sales should be a graph reflecting the trends in license plate sales.

**Comment by fawda123** [comment]
@sscolaro the BMG totals are fixed now. I also added some summary plots at the bottom to show trends over time. 
![image](https://user-images.githubusercontent.com/3086881/151023564-f4b63aa6-fbad-4db6-a89d-a12044b6f0bd.png)
