### ISSUE TITLE
review reach index

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/State-of-the-Bay#31]
Now that the draft pages are complete, please review them for any final edits that may be needed, including text, graphics/tables, and layout... this is the final round of edits before it goes "live". Things to consider:

* Does the text make sense? Are there any errors that need to be corrected?
* How do the graphics/tables look? Do they send a simple, high-level summary appropariate for the SOB? Are there other graphics that we could add?
* Is the layout ok (e.g., presentation of ideas, section labels, pictures to include, graph sizing , etc.)?

Page to review: https://tbep-tech.github.io/State-of-the-Bay/docs/reach-index.html

You can make edits to the Rmd file here: https://github.com/tbep-tech/State-of-the-Bay/blob/master/docs/reach-index.Rmd

Or just comment on this issue with things you'd like to see changed.

If you're happy with the existing page, just close this issue.

And don't forget to use the Project board to track progress on this issue: https://github.com/tbep-tech/State-of-the-Bay/projects/3

**Comment by fawda123** [comment]
@Tbep-Joe I have some ideas for additional graphics to include, so I'll tag team this with you.

**Comment by fawda123** [comment]
@sscolaro @Tbep-Joe I just made some very simple trend graphics for each reach summary.  Let me know what you think.  
![image](https://user-images.githubusercontent.com/3086881/152248841-4a837e85-3702-499f-8745-e77d027592f0.png)

**Comment by sscolaro** [comment]
@fawda123 I really like this! It might make it easier to tell what each line is portraying if one was a different color and there was a legend associated with it. Not sure if the legend is possible with two stacked graphs. Either way, I think this visualization is much better than the table! @Tbep-Joe

**Comment by Tbep-Joe** [comment]
This is pretty on spot with what I had in mind. I would agree with @sscolaro about the line coloring. You could just use the blue that is part of our branding. #035172 is the HEX code for that. 

I notice that the tarpon tag sales are not included. Do you need more info from me to add that?

**Comment by sscolaro** [comment]
@Tbep-Joe The Tarpon Tag sales are included on the Grants Awarded Page: [https://tbep-tech.github.io/State-of-the-Bay/docs/grants-awarded.html]

**Comment by Tbep-Joe** [comment]
Ah yes. Thanks, @sscolaro.

**Comment by fawda123** [comment]
Awesome, glad you both think this is an improvement.  I can definitely work on the colors.  

The only other thing I was thinking was maybe a brief bit of text describing what we mean by some of the metrics.  For example, "The TBEP tracks the impact of our social media output using various metrics.  Number of followers, users, or views of our content is one way we can asses how the community engages in our online platforms.  The number of engagements is another metric that we track, which includes "likes", "retweets", or other common interactions in social media."

**Comment by fawda123** [comment]
@Tbep-Joe @sscolaro just added some color and legends to the social media plots and some text from my last comment.  Please close the issue if all is good!
![image](https://user-images.githubusercontent.com/3086881/152398821-dc186229-1022-4061-9c4f-9e4801bc357b.png)

**Comment by sscolaro** [comment]
@fawda123 This is fantastic! Exactly what I was picturing. Thanks! I will let @Tbep-Joe add the index descriptor text that you mentioned, but then I think this is good to close.

**Comment by fawda123** [comment]
Cool, thanks, I added the description text already, pretty much verbatim what I had in my earlier comment.  Up to @Tbep-Joe if he wants to edit.
