### ISSUE TITLE
png wq map

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/State-of-the-Bay#40]
requesting downloadable png of the annual mapped water quality results by bay segment
![Screenshot 2024-02-01 124010](https://github.com/tbep-tech/State-of-the-Bay/assets/47223250/08672e30-f36c-4f8e-8a8e-915383f82d2f)

**Comment by fawda123** [comment]
Done https://tbep-tech.github.io/tbeptools/reference/show_sitesegmap.html, state of the bay graphic can be downloaded at https://tbep-tech.github.io/State-of-the-Bay/docs/water-quality-decision-matrix_files/figure-html/unnamed-chunk-2-1.png
