### ISSUE TITLE
nitrogen loadings

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/State-of-the-Bay#6]
Review and edit text as needed, starting here: https://github.com/tbep-tech/State-of-the-Bay/blob/955922667db0b69a2c5b3c2e97a0d9fb2c30ccc5/doc/clean-waters-and-sediments.md#L15

**Comment by fawda123** [comment]
@emseabee I took a stab at making the TN loading text more public friendly.  See the changes here 9a1f0a83f7f966d2a1f4f7f81f220375335ab4cd Curious what you think.

**Comment by emseabee** [comment]
Looks good, I tweaked a bit more. @esherwoo77 should take a look to make sure essential details weren't lost in the distillation.
